### ISSUE TITLE
Search by column 

### ISSUE THREAD

**Issue by aniskasmi** [arodygin/datatables-bundle#18] opened 2022-12-21 16:14 UTC
Hi, i want to make and search by column on my datatable for moment i have this 

```
 $('#data-table-sse thead th').each(function () {
            var title = $(this).text();
            $(this).html('<input type="text" placeholder="Search ' + title + '" />');
        });

        // DataTable
        var table = $('#data-table-sse').DataTable({
            serverSide: true,
            ajax: '{{ path('datatable_project') }}',
            initComplete: function () {
                // Apply the search
                this.api()
                    .columns()
                    .every(function () {
                        var that = this;

                        $('input', this.footer()).on('keyup change clear', function () {
                            if (that.search() !== this.value) {
                                that.search(this.value).draw();
                            }
                        });
                    });
            },
        });
```

And this on handle
```
 foreach ($request->columns as $column) {
            if ($column->search->value) {
                $value = strtolower($column->search->value);
                // "Login" column
                if ($column->data == 2) {
                    $query->andWhere('p.serial_number LIKE :search');
                    $query->setParameter('search', "%{$value}%");
                }
                if ($column->data == 3) {
                    $query->andWhere('p.order_number LIKE :search');
                    $query->setParameter('search', "%{$value}%");
                }
            }
        }
```

But when he have only and column define on handle is working, but when i put an second column, the handle don't made the difference between column data == 2 & data == 3 and launch two $query->andWhere()

![image](https://user-images.githubusercontent.com/10786016/208951477-c065f674-08cf-4879-b1d3-b7649df63482.png)

Do you have and exemple of JS Code to Column Search or any information about this issue thx

**Comment by aniskasmi** [comment] 2022-12-21 16:21
For example i add dump('HIT') and dump('HIT x2') on every handle column 

```
foreach ($request->columns as $column) {
            if ($column->search->value) {
                $value = strtolower($column->search->value);
                // "Login" column
                if ($column->data == 2) {
                    dump('HIT');
                    $query->andWhere('p.serial_number LIKE :search');
                    $query->setParameter('search', "%{$value}%");
                }
                if ($column->data == 3) {
                    dump('HIT x2');
                    $query->andWhere('p.order_number LIKE :search');
                    $query->setParameter('search', "%{$value}%");
                }
            }
        }
```

When i put an search on just one column the two dump is hit
![image](https://user-images.githubusercontent.com/10786016/208953531-3adc92da-291d-47eb-8311-b1b30db3ca32.png)

![image](https://user-images.githubusercontent.com/10786016/208953603-e9064c0c-86ba-4815-bfac-40542e748706.png)

How to identity the column search only and process the $query->andWhere only when the correct column is hit 

Thx a lot

**Comment by webinarium** [comment] 2022-12-22 03:37
Hi,

I would recommend checking:
- what exactly the request, generated by DataTable plugin, contains in its payload (using browser's network console)
- if the request is fine, what actually has been received in the `DataTableQuery $request` object.

I'm pretty sure it's a frontend issue, so you may find the request is wrong. Also, I have a thought about what exactly can be wrong there, but I can be wrong. What looks suspicious to me is this line in your JavaScript code:
```
$('input', this.footer())...
```

As far as I can see, you took this whole piece of code from [original DataTables example](https://datatables.net/reference/api/columns().every()). That example supposes you have your filters in the `tfoot` tag, while you're adding them in the `thead` one, moreover you don't have `tfoot` at all. As result:
- `this.footer()` returns `null`
- `$('input', null /*this.footer()*/)` returns all your inputs
- further call of `$('input', this.footer()).on('keyup change clear', ...)` assigns a callback to all your inputs
- each time a user enters something in one input, the entered value is assigned to all your filters at once.

As a solution, I would just replace `this.footer()` with `this.header()` - it should help, if I understood the root cause right. Otherwise, please provide me with the generated payload and the `DataTableQuery $request` object's dump.

**Closed as completed** 2022-12-22 23:39 UTC
Labels: support
